spring:
  profiles:
    active: dev
server:
  port: 8000


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/uaa/user
---

spring:
  profiles: dev
  data:
   mongodb:
      database: trueyes-dev

---

spring:
  profiles: prod
  data:
   mongodb:
      database: trueyes-prod