spring:
  profiles:
    active: dev
server:
  port: 8000

---

spring:
  profiles: dev
  data:
   mongodb:
      database: trueyes-dev

---

spring:
  profiles: prod
  data:
   mongodb:
      database: trueyes-prod